# Generated by Django 2.1.3 on 2018-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeqDHBM', '0002_auto_20181123_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='status',
            new_name='status_hbm',
        ),
        migrations.AddField(
            model_name='sequence',
            name='fasta_file_location',
            field=models.FilePathField(default='4', path='/home/mau/work/hemesite'),
            preserve_default=False,
        ),
    ]
