# Generated by Django 2.1.3 on 2018-11-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeqDHBM', '0003_auto_20181123_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Result_HBM',
        ),
    ]
