# Generated by Django 2.1.3 on 2018-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeqDHBM', '0005_sequence_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_hbm',
            name='net_charge',
            field=models.CharField(max_length=20),
        ),
    ]
