# Generated by Django 2.1.1 on 2018-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeqDHBM', '0007_sequence_warnings_hbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='fasta_file_location',
            field=models.FilePathField(path='/home/imhof_team/Public/git/hemesite'),
        ),
    ]
