# Generated by Django 2.1.1 on 2018-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeqDHBM', '0008_auto_20181206_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='partial_hbm_analysis',
            field=models.TextField(blank=True),
        ),
    ]
